apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- log-deployment
images:
- name: gcr.io/dwk-gke-450416/logging
  newName: gcr.io/dwk-gke-450416/logging
  newTag: main-335809a62c25e363d9a6abb2db607ca835b99b2b
