apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- log-deployment
namespace: ping-pong-uuid
images:
- name: gcr.io/dwk-gke-450416/logging
  newName: gcr.io/dwk-gke-450416/logging
  newTag: main-6af5571750bb85204f1e5e3a38fb42b1860d515d
