apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- log-deployment.yaml
- ingress.yaml
- database-config.yaml
- backendconfig.yaml
images:
- name: gcr.io/dwk-gke-450416/logging
  newName: gcr.io/dwk-gke-450416/logging
  newTag: main-bbbce524afe9d6f9f06a54a7ed0711c4fad983a1
