apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- log-deployment.yaml
- ingress.yaml
- postgres-secrets.yaml
- statefulset.yaml
- backendconfig.yaml
images:
- name: gcr.io/dwk-gke-450416/logging
  newName: gcr.io/dwk-gke-450416/logging
  newTag: main-4272425548dae966237fea48f34e35411b581db6
