apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - log-deployment
images:
- name: LOGGING/IMAGE
  newName: gcr.io/dwk-gke-416915/backend:main-0d5844ab22796f0e571912d19da2962392192bbf
